import "./globals.css";


export const metadata: Metadata = {
  title: "MAU1",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
